services:
  sosubot-service:
    build:
      context: .
      dockerfile: ./SosuBot/Dockerfile
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 1
    environment:
      REDIS_HOST: redis-service
      DB_HOST: db-service
      DB_PORT: 5432
      DB_NAME: sosubot
      DB_USER: sosubot
      DB_PASSWORD_FILE: /run/secrets/db-password
      DB_MIGRATE: "NO"
      USE_POSTGRES: "YES"
    secrets:
      - db-password
    expose:
      - "5000"
    volumes:
      - ./cache:/app/cache
    depends_on:
      db-service:
        condition: service_healthy
      redis-service: 
        condition: service_healthy
    networks:
      - app-network
      
  
  redis-service:
    image: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
    volumes:
      - ./.redis/data:/data
      - ./.redis/redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - app-network
    

  db-service:
    image: postgres:17-alpine
    restart: unless-stopped
    secrets:
      - db-password
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sosubot
      POSTGRES_USER: sosubot
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "sosubot", "-d", "sosubot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    

secrets:
  db-password:
    file: .secrets/.db_password
    

networks:
  app-network:
    enable_ipv6: true
    driver: bridge